### ISSUE TITLE
Painterro prevents page scrolling on mobile browser

### ISSUE THREAD

**Issue by afaonline** [ivictbor/painterro#14]
Page with Painterro does not scroll on mobile browsers. When user clicks "close" button in Paiterro, the page can scroll again. 

Reproduced on Chrome for Android, Safari on iOS and in Device Mode on Desktop Chrome (Windows 10)

**Comment by ivictbor** [comment]
Hi, thanks for the report.
Yes, this is because of deliberate overflow-y: hidden applied to body when Painterro is open (https://github.com/ivictbor/painterro/blob/master/js/main.js#L851) to prevent page refresher in mobile chrome when the user, for example, draws a line from top to bottom. Here is details https://stackoverflow.com/questions/29008194/disabling-androids-chrome-pull-down-to-refresh-feature . simple preventDefaults does not help to stop reloader it requires some tricky handing, but definitely, we need to find a better way to allow scrolling

**Comment by ivictbor** [comment]
I was not able to find a better way to prevent reloader, so what I can suggest is `fixMobilePageReloader` that was added in v0.2.61. 
@afaonline Just set `fixMobilePageReloader` option to `false` and you will be able to scroll again. Currently, it defaults to `true`, but I think it will be changed to `false` in 0.3.x

**Comment by afaonline** [comment]
It works now!  Page scrolling fixed, page reloading by pull down also works

Thank you very much!

**Comment by kishandonepudi** [comment]
how to include painterro in full page instead of a pop-up?

now i am using  Painterro({}).show()
