### ISSUE TITLE
Inserted text issue: selected position and placed position mismatch

### ISSUE THREAD

**Issue by kishandonepudi** [ivictbor/painterro#35]
I had an issue, while playing on with insert text feature.

I have selected a position and entered a few words and when i press on tick mark(i.e ok) the text size is getting enlarged and also the placed position varies with the one i wanted to be.

like as below 

![1](https://user-images.githubusercontent.com/17450660/46464864-04658380-c7e5-11e8-968a-98162beeae08.JPG)

![2](https://user-images.githubusercontent.com/17450660/46464871-06c7dd80-c7e5-11e8-8db7-48a449dc1287.JPG)

any solution for this?

**Comment by ivictbor** [comment]
Hi @kishandonepudi thanks for bug report!

**Comment by bhuwangothe** [comment]
you have a very good plugin.
but i got stuck because of this text insert issue.
text sizes changes randomly and the position too.
is it already fixed or you are still on it.
I am desperately waiting for the fix.
if you could let me know the source of issue, may be i would give it a try for fix.
let me know :)

**Comment by ivictbor** [comment]
@bhuwangothe , please try now, a lot of text issues were solved in latest releases.
Issue were:
- in different scale modes (e.g. image larger then viewport was loaded into widget)
- at different zoom level

**Comment by ivictbor** [comment]
@kishandonepudi fixed, please try and let me know
